### ISSUE TITLE
undefined local variable or method `per' for []:ActiveRecord::Relation

### ISSUE THREAD

**Issue by jplethier** [kiddsoftware/rails_blog_engine#3]
I installed the gem, run the generator, and when I go to the /blog, i see this error: undefined local variable or method `per' for []:ActiveRecord::Relation

The full stack is: 

activerecord (3.1.1) lib/active_record/relation.rb:459:in `method_missing'
rails_blog_engine (0.0.4) app/controllers/rails_blog_engine/posts_controller.rb:10:in`block (2 levels) in index'
actionpack (3.1.1) lib/action_controller/metal/mime_responds.rb:195:in `call'
actionpack (3.1.1) lib/action_controller/metal/mime_responds.rb:195:in`respond_to'
rails_blog_engine (0.0.4) app/controllers/rails_blog_engine/posts_controller.rb:9:in `index'
actionpack (3.1.1) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.1.1) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.1.1) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.1.1) lib/abstract_controller/callbacks.rb:18:in `block in process_action'

**Comment by jplethier** [comment]
I don't know if the problema is because I use the act_as_commentable gem to add comments in my application, and the rails_blog_engine gem has a model with the same name.

If the problem is that, what can I do to fix this problem and use the rails_blog_engine gem too

**Comment by jplethier** [comment]
The problem looks like it is the db post table is blank, so when the action index of post controller is called, the method per is called in a nil value, cause the list is nil.

**Comment by djhopper01** [comment]
If you check your bundle list, do you also have both the kaminari and will_paginate gems installed? This is a known conflict between kaminari and will_paginate.

Read and try this to see if you can get it working:
https://github.com/mislav/will_paginate/issues/174#issuecomment-4475139

**Comment by jplethier** [comment]
the rails_blog_engine use the kaminari? cause I didn't remember to install the kaminari by myself in my project.

**Comment by jplethier** [comment]
Solved, thanks for the answer, I didn't see that rails_blog_engine uses kaminari.
